### ISSUE TITLE
404 Not Found when user tries to access a poll that does not exist

### ISSUE THREAD

**Issue by OmegaOoh** [caneledip/ku-polls#46]
![image](https://github.com/user-attachments/assets/13c70e7c-f585-4628-9cad-02ab34ceffb7)

When the user tries to access the poll that does not exist or isn't published, it should redirect the user to the polls index page with an error message to tell the user why they got redirected.

**Comment by caneledip** [comment]
Access to non existed poll will now redirect to polls index with descriptive message
