### ISSUE TITLE
Number of vote is hard to see

### ISSUE THREAD

**Issue by OmegaOoh** [caneledip/ku-polls#47]
![image](https://github.com/user-attachments/assets/55f33b58-30e9-4ea4-95ec-036469052992)

It is hard to see the number of votes for each choice on the results page. You may need to adjust the background or add the overlay to make the choice and its number of votes stand out from the background.

The location of vote count is on the most right of the screen which is hard to find.

**Comment by caneledip** [comment]
![image](https://github.com/user-attachments/assets/05ee8eeb-4426-4e66-8d62-72f9f2f72e8d)
I have change it to be more visible now
