### ISSUE TITLE
No update on count of vote after voting

### ISSUE THREAD

**Issue by OmegaOoh** [caneledip/ku-polls#48]
### When I vote for poll number 4 it does not update, and it looks like it does not save the vote at all

![vote-poll-4](https://github.com/user-attachments/assets/bf068ea8-ae91-4ebe-9785-d2aa315fa871)

### Vote does not update with another account than demo1

**Demo1 Initial Vote**
![demo1-initial](https://github.com/user-attachments/assets/528db156-4549-4807-9e0b-eea229bd249b)

**Demo1 update Vote**
![demo1-update](https://github.com/user-attachments/assets/ac925685-3ebb-4fea-bfc9-85d6557c6ba9)

**But** when voting with another account (demo2 for example), the vote does not add up.
![demo2-vote](https://github.com/user-attachments/assets/de0e634c-d7a5-46e4-9fc4-908e6a62d7ee)

**After** investigation, the User can't cast a new vote but can update their vote.

**Comment by caneledip** [comment]
The issue have been fixed.
