### ISSUE TITLE
Code Styling Issues.

### ISSUE THREAD

**Issue by OmegaOoh** [caneledip/ku-polls#50]
![flake-8](https://github.com/user-attachments/assets/dc17e902-62e7-4e39-bdf9-85334919bb96)

There are a lot of problems when I lint with `flake8` and `flake8-docstrings`.

You can also add the `flake8-docstrings` package in `style-checking.yml` to use it in GitHub actions.
The `pytest` installation in `style-checking.yml` is redundant.

**Comment by caneledip** [comment]
Thanks for advice, I just realize I don't have flake8-docstrings install. This help a lot.
It is fixed, excepted for E501 I increase max-line-length up to 127
